### ISSUE TITLE
Test suite failure; no host header in request

### ISSUE THREAD

**Issue by moretea** [creativesoftwarefdn/weaviate#364]
```
$ vgo test test/full_test.go 
--- FAIL: Test__weaviate_GET_meta_JSON_internal (0.00s)
panic: Get http:///weaviate/v1/meta: http: no Host in request URL [recovered]
	panic: Get http:///weaviate/v1/meta: http: no Host in request URL

goroutine 4 [running]:
testing.tRunner.func1(0xc4204781e0)
	/nix/store/nyry420bm3ic5yfpka2p4r80zc0w0i3g-go-1.10.1/share/go/src/testing/testing.go:742 +0x29d
panic(0x77e1a0, 0xc4202e98c0)
	/nix/store/nyry420bm3ic5yfpka2p4r80zc0w0i3g-go-1.10.1/share/go/src/runtime/panic.go:502 +0x229
command-line-arguments.doRequest(0x7e0369, 0x5, 0x7df499, 0x3, 0x7e7c83, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
	/home/maarten/.go_workspaces/7393e365f7a16dbf0731476577dba057f7cc18aace8c42e06f9eb9ed8bd48683/src/github.com/creativesoftwarefdn/weaviate/test/full_test.go:65 +0x2c0
command-line-arguments.Test__weaviate_GET_meta_JSON_internal(0xc4204781e0)
	/home/maarten/.go_workspaces/7393e365f7a16dbf0731476577dba057f7cc18aace8c42e06f9eb9ed8bd48683/src/github.com/creativesoftwarefdn/weaviate/test/full_test.go:228 +0xaa
testing.tRunner(0xc4204781e0, 0x803508)
	/nix/store/nyry420bm3ic5yfpka2p4r80zc0w0i3g-go-1.10.1/share/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/nix/store/nyry420bm3ic5yfpka2p4r80zc0w0i3g-go-1.10.1/share/go/src/testing/testing.go:824 +0x2e0
FAIL	command-line-arguments	0.020s

```

**Comment by moretea** [comment]
The test suite is an end-to-end integration test suite.
